config/routes.rb
LDT::Application.routes.draw do
  resources :expos

  resources :furnitures

  get "home/index"
  get "contact/index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :users

  root :to => 'furnitures#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/expo.rb
class Expo < ActiveRecord::Base
  attr_accessible :address, :city, :date_time, :description, :title
end

app/models/findme.rb
class Findme < ActiveRecord::Base
  attr_accessible :address, :description, :name_location, :photo, :title
end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
  attr_accessible :furniture

# This method associates the attribute ":avatar" with a file attachment                                             
  has_attached_file :photo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/expos_controller.rb
class ExposController < InheritedResources::Base
respond_to :xml, :json, :html

def index

      @expos = Expo.all

      respond_with(@expos)
    end

    def new
      @expo = Expo.new
      respond_with(@expo)
    end

    def create
      @expo = Expo.create(params[:expo])
      respond_with(@expo)
    end

    def edit
      @expo = Expo.find(params[:id])
      respond_with(@expo)
    end


    def show
      @expo = Expo.find(params[:id])
      respond_with(@expo)
    end

    def update
        @expo = Expo.find(params[:id])
        @expo.update_attributes(params[:expo])
        respond_with(@expo)
    end

    def destroy
        @expo = Expo.find(params[:id]).destroy
        respond_with(@expo)
    end

end

app/controllers/findmes_controller.rb
class FindmesController < InheritedResources::Base
end

app/controllers/furnitures_controller.rb
class FurnituresController < InheritedResources::Base
respond_to :xml, :json, :html

def index

      @furnitures = Furniture.all

      respond_with(@furnitures)
    end

    def new
      @furniture = Furniture.new
      respond_with(@furniture)
    end

    def create
      @furniture = Furniture.create(params[:furniture])
      respond_with(@furniture)
    end

    def edit
      @furniture = Furniture.find(params[:id])
      respond_with(@furniture)
    end


    def show
      @furniture = Furniture.find(params[:id])
      respond_with(@furniture)
    end

    def update
        @furniture = Furniture.find(params[:id])
        @furniture.update_attributes(params[:furniture])
        respond_with(@furniture)
    end

    def destroy
        @furniture = Furniture.find(params[:id]).destroy
        respond_with(@furniture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:error, :info, :success, :warning]

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?
      
      type = :success if type == :notice
      type = :error if type == :alert
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/expos_helper.rb
module ExposHelper
end

app/helpers/findmes_helper.rb
module FindmesHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/index.html.erb
<% content_for :pagetitle do %>
  Contact
<% end %>

<% content_for :pagecontent do %>
  <div class="row">
    <div class="large-9 columns">
 
      <h3>Contact our Company</h3>
      
          <div class="content" data-slug="panel1">
            <form>
              <div class="row collapse">
                <div class="large-2 columns">
                  <label class="inline">Your Name</label>
                </div>
                <div class="large-10 columns">
                  <input type="text" id="yourName" placeholder="Jane Smith">
                </div>
              </div>
              <div class="row collapse">
                <div class="large-2 columns">
                  <label class="inline"> Your Email</label>
                </div>
                <div class="large-10 columns">
                  <input type="text" id="yourEmail" placeholder="jane@smithco.com">
                </div>
              </div>
              <label>What's up?</label>
              <textarea rows="4"></textarea>
              <button type="submit" class="radius button">Submit</button>
            </form>

      </div>
    </div>

    <div class="large-3 columns">
      <h3>Map</h3>
      <!-- Clicking this placeholder fires the mapModal Reveal modal -->
      <p>
        <a href="" data-reveal-id="mapModal"><img src="http://placehold.it/400x280"></a><br />
        <a href="" data-reveal-id="mapModal">View Map</a>
      </p>
      <p>
        123 Awesome St.<br />
        Barsoom, MA 95155
      </p>
    </div>
    <!-- End Sidebar -->
  </div>
  </div>
<% end %>

app/views/expos/_form.html.erb
<%= form_for(@expo) do |f| %>
  <% if @expo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expo.errors.count, "error") %> prohibited this expo from being saved:</h2>

      <ul>
      <% @expo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_time %><br />
    <%= f.datetime_select :date_time %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expos/edit.html.erb
<h1>Editing expo</h1>

<%= render 'form' %>

<%= link_to 'Show', @expo %> |
<%= link_to 'Back', expos_path %>

app/views/expos/index.html.erb
<h1>Listing expos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date time</th>
    <th>Address</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expos.each do |expo| %>
  <tr>
    <td><%= expo.title %></td>
    <td><%= expo.description %></td>
    <td><%= expo.date_time %></td>
    <td><%= expo.address %></td>
    <td><%= expo.city %></td>
    <td><%= link_to 'Show', expo %></td>
    <td><%= link_to 'Edit', edit_expo_path(expo) %></td>
    <td><%= link_to 'Destroy', expo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expo', new_expo_path %>

app/views/expos/new.html.erb
<h1>New expo</h1>

<%= render 'form' %>

<%= link_to 'Back', expos_path %>

app/views/expos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @expo.title %>
</p>

<p>
  <b>Description:</b>
  <%= @expo.description %>
</p>

<p>
  <b>Date time:</b>
  <%= @expo.date_time %>
</p>

<p>
  <b>Address:</b>
  <%= @expo.address %>
</p>

<p>
  <b>City:</b>
  <%= @expo.city %>
</p>


<%= link_to 'Edit', edit_expo_path(@expo) %> |
<%= link_to 'Back', expos_path %>

app/views/findmes/_form.html.erb
<%= form_for(@findme) do |f| %>
  <% if @findme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@findme.errors.count, "error") %> prohibited this findme from being saved:</h2>

      <ul>
      <% @findme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :name_location %><br />
    <%= f.text_field :name_location %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/findmes/edit.html.erb
<h1>Editing findme</h1>

<%= render 'form' %>

<%= link_to 'Show', @findme %> |
<%= link_to 'Back', findmes_path %>

app/views/findmes/index.html.erb
<h1>Listing findmes</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Name location</th>
    <th>Address</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @findmes.each do |findme| %>
  <tr>
    <td><%= findme.title %></td>
    <td><%= findme.description %></td>
    <td><%= findme.name_location %></td>
    <td><%= findme.address %></td>
    <td><%= findme.photo %></td>
    <td><%= link_to 'Show', findme %></td>
    <td><%= link_to 'Edit', edit_findme_path(findme) %></td>
    <td><%= link_to 'Destroy', findme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Findme', new_findme_path %>

app/views/findmes/new.html.erb
<h1>New findme</h1>

<%= render 'form' %>

<%= link_to 'Back', findmes_path %>

app/views/findmes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @findme.title %>
</p>

<p>
  <b>Description:</b>
  <%= @findme.description %>
</p>

<p>
  <b>Name location:</b>
  <%= @findme.name_location %>
</p>

<p>
  <b>Address:</b>
  <%= @findme.address %>
</p>

<p>
  <b>Photo:</b>
  <%= @findme.photo %>
</p>


<%= link_to 'Edit', edit_findme_path(@findme) %> |
<%= link_to 'Back', findmes_path %>

app/views/furnitures/_form.html.erb
<%= form_for @furniture, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :order_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :order_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_file_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_file_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_content_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :photo_content_type, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_file_size, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :photo_file_size, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo_updated_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :photo_updated_at, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    furnitures_path, :class => 'btn' %>
  </div>
<% end %>

app/views/furnitures/edit.html.erb
<h1>Editing furniture</h1>

<%= render 'form' %>

<%= link_to 'Show', @furniture %> |
<%= link_to 'Back', furnitures_path %>

app/views/furnitures/index.html.erb
<% content_for :pagetitle do %>
  Furniture
<% end %>

<% content_for :pagecontent do %>
<div class="row">
<% @furnitures.each do |furniture| %>

  <div class="large-4 columns">
    <div class="panel">
      <p>
	<%= link_to image_tag("http://placehold.it/400x300"), furniture %>

<!--      <h4><%= furniture.title %></h4>
      <p><%= furniture.description %></p>
      <p><%= furniture.photo %></p>
      <tr>
	<td><%= link_to 'Show', furniture %></td>
	<td><%= link_to 'Edit', edit_furniture_path(furniture) %></td>
	<td><%= link_to 'Destroy', furniture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
      </p>
    </div>
  </div>
<% end %>
</div>
<% end %>

app/views/furnitures/new.html.erb
<% content_for :pagetitle do %>
  New Furniture POWWAAA
<% end %>

<% content_for :pagecontent do %>
  <div class="row">
    
    <div class="small-12 columns"><img src="http://placehold.it/1200x400"></div>
    
    <div class="small-12 columns"><h2>Adopte un bot en trois étapes</h2></div>
    
    <%= render 'form' %>
  </div>
  <% end %>

app/views/furnitures/show.html.erb
<% content_for :pagetitle do %>
    <%= @furniture.title %>
<% end %>

<% content_for :pagecontent do %>
  <div class="row">
    <div class="large-6 columns">
      <img src="http://placehold.it/500x500&text=Image"><br>
    </div>

    <div class="large-6 columns">
      <h3 class="show-for-small"><%= @furniture.title %> <hr/></h3>
      <div class="panel">
        <h4 class="hide-for-small"><%= @furniture.order_type %><hr/></h4>
	<h5 class="subheader"><%= @furniture.description %></h5>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<% content_for :pagetitle do %>
  Accueil
<% end %>

<% content_for :pagecontent do %>
  <div class="row">

  	<div class="small-12 columns"><img src="http://placehold.it/1200x400"></div>

	<div class="small-12 columns"><h2>Adopte un bot en trois étapes</h2></div>

  	<div class="small-12 large-4 columns">
  		<div class="panel radius">
	  		<h4>1 - L'inscription</h4>
	  		<p>Lorem ipsum sin dolor est erectum cartage delenta estumis despues est minoritis aquae doloret</p>
  		</div>
  	</div>

  	<div class="small-12 large-4 columns">
  		<div class="panel radius">
	  		<h4>2 - Devenez premium !</h4>
	  		<p>Lorem ipsum sin dolor est erectum cartage delenta estumis despues est minoritis aquae doloret</p>
  		</div>
  	</div>

  	<div class="small-12 large-4 columns">
  		<div class="panel radius">
	  		<h4>3 - Devenez irrésistible !</h4>
	  		<p>Lorem ipsum sin dolor est erectum cartage delenta estumis despues est minoritis aquae doloret</p>
  		</div>
  	</div>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
  <input type="file" accept="image/*" capture="camera">

</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @user.password %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>